### ISSUE TITLE
0.1.4 not work

### ISSUE THREAD

**Issue by sylus28** [BCN3D/BCN3D-Cura-Mac#4]
test on my macbook ,unable to start

01/04/2016 00:01:47,851 Cura-BCN3D[12965]: GLUT Warning: glutInit being called a second time.
01/04/2016 00:01:47,851 Cura-BCN3D[12965]: 2016-04-01 00:01:47.851 Cura-BCN3D[12965:1573590] GLUT Warning: glutInit being called a second time.
01/04/2016 00:01:47,931 Cura-BCN3D[12965]: My current version is  0.1.4
01/04/2016 00:01:48,624 Cura-BCN3D[12965]: Traceback (most recent call last):
01/04/2016 00:01:48,624 Cura-BCN3D[12965]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/**boot**.py", line 351, in <module>
01/04/2016 00:01:48,624 Cura-BCN3D[12965]:     _run()
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/__boot__.py", line 336, in _run
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:     exec(compile(source, path, 'exec'), globals(), globals())
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 89, in <module>
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:     main()
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "/Applications/Cura/Cura-BCN3D.app/Contents/Resources/cura.py", line 86, in main
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:     app.CuraApp(args).MainLoop()
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "Cura/gui/app.pyo", line 59, in __init__
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "Cura/gui/app.pyo", line 142, in afterSplashCallback
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "Cura/util/version.pyo", line 250, in checkForNewVersion
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "urllib2.pyo", line 154, in urlopen
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "urllib2.pyo", line 431, in open
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "urllib2.pyo", line 449, in _open
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "urllib2.pyo", line 409, in _call_chain
01/04/2016 00:01:48,625 Cura-BCN3D[12965]:   File "urllib2.pyo", line 1240, in https_open
01/04/2016 00:01:48,626 Cura-BCN3D[12965]:   File "urllib2.pyo", line 1197, in do_open
01/04/2016 00:01:48,626 Cura-BCN3D[12965]: urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
01/04/2016 00:01:48,691 Cura-BCN3D[12965]: Cura-BCN3D Error
01/04/2016 00:01:48,691 Cura-BCN3D[12965]: 2016-04-01 00:01:48.691 Cura-BCN3D[12965:1573590] Cura-BCN3D Error
01/04/2016 00:01:52,142 sharedfilelistd[310]: SecTaskLoadEntitlements failed error=22

**Comment by remelbourne** [comment]
@sylus28 I just uploaded a new version. Can you see if it works now? Thank you.

**Comment by sylus28** [comment]
It works now thanks
